# Generated by Django 4.0.4 on 2022-05-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginPage', '0002_adminpassword_adminusername_delete_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phonenumber', models.TextField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
